version: '3.8'
name: fluentpos-lite

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGPORT=5430
    ports:
      - 5430:5430
    volumes:
      - postgres-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - fluentpos-lite

  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - fluentpos-lite

  placement:
    container_name: dapr-placement
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - 50006:50006
    networks:
      - fluentpos-lite

  redis:
    container_name: dapr-redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - fluentpos-lite
  
  elk:
    container_name:  elasticsearch-kibana
    image: sebp/elk:oss-8.5.3
    environment:
      - LOGSTASH_START=0
    volumes:
      - sebp-elk-data:/usr/share/elk/data
    ports:
      - 5601:5601
      - 9200:9200
    networks:
      - fluentpos-lite

volumes:
  postgres-data:
  mongo-data:
  sebp-elk-data:

networks:
  fluentpos-lite:
    name:  fluentpos-lite
